### ISSUE TITLE
Sound data

### ISSUE THREAD

**Issue by Cortexelus** [googlecreativelab/aiexperiments-drum-machine#3]
Are the sound files available? Are they licensed public domain / creative commons?

**Comment by kylemcdonald** [comment]
These samples were purchased by Google for this project, which means that they're not licensed for reuse.

But if you want to work with them, you could try extracting them from the publicly available data:

```sh
#!/usr/bin/env bash
mkdir -p samples
for i in {0..49}
do
	curl -O "https://aiexperiments.withgoogle.com/drum-machine/view/audio/$i.mp3"
	ffmpeg -i "$i.mp3" -f segment -segment_time 0.25 samples/"$i"_%03d.wav
	rm "$i.mp3"
done
```

This takes a couple minutes on my machine and produces a 365MB folder with 14k samples. They aren't all lined up very well, but it's a start. Scraping Freesound will give you similar or better results in my opinion.

**Comment by Cortexelus** [comment]
Thanks!
