### ISSUE TITLE
Data is absent in repo , pls explicitly describe why 

### ISSUE THREAD

**Issue by mikailcetinkaya** [googlecreativelab/aiexperiments-drum-machine#5]
Data is absent in repo , pls explicitly describe why

**Comment by EMCP** [comment]
you need to generate data yourself with either an open source set of audio data or one you generate on your own.  I think also they didn't add the data because that'd be potentially large amount of data.. for an already large project.

See 
https://github.com/kylemcdonald/AudioNotebooks

**Comment by mikailcetinkaya** [comment]
thank you very much
