### ISSUE TITLE
Forgotten file drum_like.json

### ISSUE THREAD

**Issue by codesandtags** [googlecreativelab/aiexperiments-drum-machine#6]
Hi guys,

I'm compiling the project and trying to use it, but I'm getting this error :  

ERROR in ./app/Data.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../meta/drum_like.json in /Users/codesandtags/Documents/development/workspaces/examples/aiexperiments-drum-machine/app

// Did you forgot to upload the `meta` folder ?
var drumLike = require("../meta/drum_like.json");

Thanks in advance. :)

**Comment by tambien** [comment]
This file is specific to our sound set. You'll have to generate it yourself from you samples.  

Generate your own by running `scripts/analysis.py` and then `scripts/sort_sounds.py`.

**Comment by EMCP** [comment]
@tambien I imagine we also need to create the `./ref_sounds/*` ourselves as well.. but if there's a link to those that'd be appreciated.

so far with a kick I grabbed myself in `.wav` format, gives me 

```
{"2": [0, 1, 2, 3], "3": [0, 1, 2, 3], "0": [0, 1, 2, 3], "1": [0, 1, 2, 3]}
```
